version: 2
jobs:
  build:
    working-directory: ~/RestApiAutomation
    docker:
      - image: circleci/openjdk:stretch
  
  test:
    working-directory: ~/RestApiAutomation
    steps:
      - run: ./mvn -Dmaven.test.skip=true package
workflow:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
