version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./mvn test
  build:
    docker:
      - image: circleci/openjdk:stretch
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./mvn -Dmaven.test.skip=true package
workflows:
  version: 2
  test:
    jobs:
      - test
  nightly:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "* * * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - main
    jobs:
      - test